/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NGO2024;

/**
 *
 * @author Cyrus
 */
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MenyAdmin extends javax.swing.JFrame {

    private static String ePost;
    private static String userAid;
    private InfDB idb;
    private static String aid;
    private static Validering validering;

    /**
     * Creates new form NewJFrame
     */
    public MenyAdmin(String ePost, String userAid) throws InfException {
        idb = new InfDB("ngo_2024", "3306", "dbAdmin2024", "dbAdmin2024PW");
        this.ePost = ePost;
        this.userAid = userAid;
        validering = new Validering();
        initComponents();
        fetchProjects();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabWindow = new javax.swing.JTabbedPane();
        tabTest = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        tabPersonel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        searchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SearchButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tabCountry = new javax.swing.JPanel();
        tabPartner = new javax.swing.JPanel();
        tabBranch = new javax.swing.JPanel();
        tabProject = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaprojectInformation = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout tabTestLayout = new javax.swing.GroupLayout(tabTest);
        tabTest.setLayout(tabTestLayout);
        tabTestLayout.setHorizontalGroup(
            tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTestLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(777, Short.MAX_VALUE))
        );
        tabTestLayout.setVerticalGroup(
            tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTestLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addGroup(tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(tabTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        tabWindow.addTab("test", tabTest);

        jButton8.setText("Add new personel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        searchField.setText("Search...");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Namn:");

        SearchButton1.setText("Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Epost:");

        javax.swing.GroupLayout tabPersonelLayout = new javax.swing.GroupLayout(tabPersonel);
        tabPersonel.setLayout(tabPersonelLayout);
        tabPersonelLayout.setHorizontalGroup(
            tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPersonelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchField)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPersonelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabPersonelLayout.createSequentialGroup()
                        .addComponent(SearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(SearchButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabPersonelLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        tabPersonelLayout.setVerticalGroup(
            tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPersonelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPersonelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(SearchButton1))
                .addGap(47, 47, 47)
                .addComponent(jButton8)
                .addGap(317, 317, 317)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        tabWindow.addTab("Personel", tabPersonel);

        javax.swing.GroupLayout tabCountryLayout = new javax.swing.GroupLayout(tabCountry);
        tabCountry.setLayout(tabCountryLayout);
        tabCountryLayout.setHorizontalGroup(
            tabCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        tabCountryLayout.setVerticalGroup(
            tabCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        tabWindow.addTab("Country", tabCountry);

        javax.swing.GroupLayout tabPartnerLayout = new javax.swing.GroupLayout(tabPartner);
        tabPartner.setLayout(tabPartnerLayout);
        tabPartnerLayout.setHorizontalGroup(
            tabPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        tabPartnerLayout.setVerticalGroup(
            tabPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        tabWindow.addTab("Partners", tabPartner);

        javax.swing.GroupLayout tabBranchLayout = new javax.swing.GroupLayout(tabBranch);
        tabBranch.setLayout(tabBranchLayout);
        tabBranchLayout.setHorizontalGroup(
            tabBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        tabBranchLayout.setVerticalGroup(
            tabBranchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        tabWindow.addTab("Branch", tabBranch);

        txtAreaprojectInformation.setColumns(20);
        txtAreaprojectInformation.setRows(5);
        try {
            txtAreaprojectInformation.setText(fetchProjects());
        }
        catch (InfException e) {}
        jScrollPane1.setViewportView(txtAreaprojectInformation);

        javax.swing.GroupLayout tabProjectLayout = new javax.swing.GroupLayout(tabProject);
        tabProject.setLayout(tabProjectLayout);
        tabProjectLayout.setHorizontalGroup(
            tabProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        tabProjectLayout.setVerticalGroup(
            tabProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        tabWindow.addTab("Project", tabProject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabWindow, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String personalNamn = searchField.getText();
        int index = personalNamn.indexOf(" ");
        String fornamn = personalNamn.substring(0, index);
        String efternamn = personalNamn.substring(index + 1);
        System.out.print(fornamn + efternamn);
        try {
            String sqlFraga = ("Select aid from anstalld where fornamn='" + fornamn + "' and efternamn = '" + efternamn + "';");
            String dbSqlFraga = idb.fetchSingle(sqlFraga);
            new PersonalInfo(dbSqlFraga, userAid).setVisible(true);
        } catch (Exception e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
    }//GEN-LAST:event_searchFieldActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            new NewPersonel().setVisible(true);
        } catch (InfException ex) {
            Logger.getLogger(MenyAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        // TODO add your handling code here:
        String personalEpost = searchField.getText();
       if(validering.giltigEpost(personalEpost)){
        try {
            String sqlFraga = ("Select aid from anstalld where epost ='" + personalEpost + "';");
            String dbSqlFraga = idb.fetchSingle(sqlFraga);
            new PersonalInfo(dbSqlFraga, userAid).setVisible(true);
        } catch (Exception e) {

        }
       }
    }//GEN-LAST:event_SearchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenyAdmin(ePost, userAid).setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(MenyAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

   public String fetchProjects() throws InfException {
        ArrayList<String> projektNamnLista = idb.fetchColumn("Select projektnamn from projekt;");
        ArrayList<String> projektBeskrivningLista = idb.fetchColumn("Select beskrivning from projekt;");
        ArrayList<String> projektStartdatum = idb.fetchColumn("Select startdatum from projekt;");
        ArrayList<String> projektSlutdatum = idb.fetchColumn("Select slutdatum from projekt;");
        ArrayList<String> projektKostnad = idb.fetchColumn("Select kostnad from projekt;");
        ArrayList<String> projektStatus = idb.fetchColumn("Select status from projekt;");
        ArrayList<String> projektPrioritet = idb.fetchColumn("Select prioritet from projekt;");
        ArrayList<String> projektLedareFornamn = idb.fetchColumn("select fornamn from anstalld where aid in (select projektchef from projekt);");
        ArrayList<String> projektLedareEfternamn = idb.fetchColumn("select efternamn from anstalld where aid in (select projektchef from projekt);");

        String message = "";
        String nameMessage = "Projektnamn: ";
        String descriptionMessage = "Beskrivning: ";
        String startMessage = "Startdatum: ";
        String endMessage = "Slutdatum: ";
        String costMessage = "Kostnad: ";
        String statusMessage = "Status: ";
        String priorityMessage = "Prioritet: ";
        String leaderMessage = "Projektchef: ";
        String contentName = null;
        String contentBesk = null;
        String contentStart = null;
        String contentEnd = null;
        String contentCost = null;
        String contentStatus = null;
        String contentPriority = null;
        String contentLeaderFirst = null;
        String contentLeaderLast = null; 

        for (int i = 0; i < projektNamnLista.size(); i++) {
            contentName = projektNamnLista.get(i);
            contentBesk = projektBeskrivningLista.get(i);
            contentStart = projektStartdatum.get(i);
            contentEnd = projektSlutdatum.get(i);
            contentCost = projektKostnad.get(i);
            contentStatus = projektStatus.get(i);
            contentPriority = projektPrioritet.get(i);
            contentLeaderFirst = projektLedareFornamn.get(i);
            contentLeaderLast = projektLedareEfternamn.get(i);
            message = message + "\n" + nameMessage + contentName + "\n" + descriptionMessage + contentBesk + "\n" + startMessage + contentStart + "\n" + endMessage + contentEnd + "\n" + costMessage + contentCost + "\n" + statusMessage + contentStatus + "\n" + priorityMessage + contentPriority + "\n" + leaderMessage + contentLeaderFirst + " " + contentLeaderLast + "\n"; 
        }
        
        return message.trim();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SearchButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel tabBranch;
    private javax.swing.JPanel tabCountry;
    private javax.swing.JPanel tabPartner;
    private javax.swing.JPanel tabPersonel;
    private javax.swing.JPanel tabProject;
    private javax.swing.JPanel tabTest;
    private javax.swing.JTabbedPane tabWindow;
    private javax.swing.JTextArea txtAreaprojectInformation;
    // End of variables declaration//GEN-END:variables
}
