package NGO2024;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import NGO2024.validering;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import java.util.*;
import oru.inf.InfDB;

/**
 * Klass som lägger till ny personal. TODO Validera altl och tänk ett steg
 * ytterligare på formateringen. Troligen bör den gå igenom någon typ av
 * validering den med. Möjligen att vi skriver att char at index 4/7 MÅSTE vara
 * - Char at 1 , 2 , 3, 5 , 6 , 8, 9 måste vara int eller char 0123456789. Kan
 * göras med en loop! en ifFound loop som returnar true. plus logik WIP
 *
 * @author Cyrus
 * @version 10/05/2024
 */
public class NewLand extends javax.swing.JFrame {

    private InfDB idb;
    private static String userAid;
    private static validering validering;

    /**
     * Creates new form newPersonel
     *
     * @throws oru.inf.InfException
     */
    public NewLand(String userAid) throws InfException {

        this.userAid = userAid;
        validering = new validering();

        try {
            idb = new InfDB("ngo_2024", "3306", "dbAdmin2024", "dbAdmin2024PW");

        } catch (InfException ex) {
            Logger.getLogger(NewLand.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        wrongFormat.setVisible(false);
    }

    /* public String setUserName() throws InfException{
    String userName = idb.fetchSingle("select concat(fornamn, efternamn) from anstalld where aid ="+userAid+";");
    return userName;
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        countryName = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        timezoneField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        politicField = new javax.swing.JTextArea();
        languageField = new javax.swing.JTextField();
        currencyField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        economicField = new javax.swing.JTextArea();
        wrongFormat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        countryName.setText("Country name");
        countryName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryNameMouseClicked(evt);
            }
        });
        countryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryNameActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("New country");

        timezoneField.setText("Timezone");
        timezoneField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timezoneFieldMouseClicked(evt);
            }
        });
        timezoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timezoneFieldActionPerformed(evt);
            }
        });

        politicField.setColumns(20);
        politicField.setRows(5);
        politicField.setText("Political structure");
        jScrollPane1.setViewportView(politicField);

        languageField.setText("Language");
        languageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageFieldActionPerformed(evt);
            }
        });

        currencyField.setText("Currency");

        economicField.setColumns(20);
        economicField.setRows(5);
        economicField.setText("Economical structure");
        jScrollPane2.setViewportView(economicField);

        wrongFormat.setText("Currency wrong format. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timezoneField)
                    .addComponent(currencyField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(countryName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(wrongFormat)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(countryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timezoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(createButton)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryNameMouseClicked
        if (countryName.getText().equals("Name")) {
            countryName.setText("");
        }
    }//GEN-LAST:event_countryNameMouseClicked

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String newCountryName = countryName.getText();
        String newPolitical = politicField.getText();
        String newEconomic = economicField.getText();
        String newCurrency = currencyField.getText();
        String newTimeZone = timezoneField.getText();
        String newLanguage = languageField.getText();

        //TODO
        String newLid;

        try {
            newLid = idb.getAutoIncrement("land", "lid");
            String sqlQuerry = ("INSERT INTO ngo_2024.land (lid) VALUES (" + newLid + ");");
            idb.insert(sqlQuerry);
            //använd valideringsklass
            if (validering.fieldValidation(newCountryName, "Country name")) {
                insertValue("namn", newCountryName, newLid);
            }
            //använd valideringsklass
            if (validering.fieldValidation(newPolitical, "-1")) {
                insertValue("politisk_struktur", newPolitical, newLid);
            }
            if (validering.fieldValidation(newEconomic, "-1")) {
                insertValue("ekonomi", newEconomic, newLid);
            }
            if (validering.fieldValidation(newTimeZone, "Timezone")) {
                insertValue("tidszon", newTimeZone, newLid);
            }

            if (validering.fieldValidation(newLanguage, "Language")) {
                insertValue("sprak", newLanguage, newLid);
            }

            //använd valideringsklass
            if (validering.fieldValidation(newCurrency, "Valuta")) {
                if (newCurrency.contains(".")) {
                    insertValue("valuta", newCurrency, newLid);
                } else {
                        wrongFormat.setVisible(true);
                }
            }

            /* tänk
            if (fieldValidation(newCountry, "Contact field of operations")) {
                insertValue("Branch", newCountry, newPid);
            }*/
        } catch (InfException ex) {
            Logger.getLogger(NewLand.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void timezoneFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timezoneFieldMouseClicked
        if (timezoneField.getText().equals("City")) {
            timezoneField.setText("");
        }
    }//GEN-LAST:event_timezoneFieldMouseClicked

    private void countryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryNameActionPerformed

    private void timezoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timezoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timezoneFieldActionPerformed

    private void languageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageFieldActionPerformed

    private void insertValue(String column, String value, String newLid) throws InfException {
        String sqlQuerry = ("UPDATE ngo_2024.land t SET t." + column + " = '" + value + "' WHERE t.lid = " + newLid + ";");
        idb.update(sqlQuerry);
    }

    /**
     * TODO ändra till land
     *
     * @param newCity
     * @param newPid
     * @throws InfException
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewLand(userAid).setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(NewLand.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField countryName;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField currencyField;
    private javax.swing.JTextArea economicField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField languageField;
    private javax.swing.JTextArea politicField;
    private javax.swing.JTextField timezoneField;
    private javax.swing.JLabel wrongFormat;
    // End of variables declaration//GEN-END:variables
}
