/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NGO2024;

import NGO2024.Validering;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import java.util.*;
import javax.swing.JFrame;
import oru.inf.InfDB;

/**
 * Klass som lägger till ny personal. TODO Validera altl och tänk ett steg
 * ytterligare på formateringen. Troligen bör den gå igenom någon typ av
 * validering den med. Möjligen att vi skriver att char at index 4/7 MÅSTE vara
 * - Char at 1 , 2 , 3, 5 , 6 , 8, 9 måste vara int eller char 0123456789. Kan
 * göras med en loop! en ifFound loop som returnar true. plus logik WIP
 *
 * @author Cyrus
 * @version 10/05/2024
 */
public class NewPersonel extends javax.swing.JFrame {

    private InfDB idb;
    private static int aid;
    private static int userAid;
    private static Validering validering;
   

    /**
     * Creates new form newPersonel
     *
     * @throws oru.inf.InfException
     */
    public NewPersonel() throws InfException {

        validering = new Validering();

        try {
            idb = new InfDB("ngo_2024", "3306", "dbAdmin2024", "dbAdmin2024PW");
        } catch (InfException ex) {
            Logger.getLogger(PersonalInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        jLblErrorMessageDate1.setVisible(false);
        jLblErrorMessageDate2.setVisible(false);
        lblErrorMessageAvd1.setVisible(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        adressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneNumField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        lblPersonelDetails = new javax.swing.JLabel();
        jTxtAvdelning = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAvdelningarna = new javax.swing.JTextArea();
        dateOfEmploymentField = new javax.swing.JTextField();
        jLblErrorMessageDate1 = new javax.swing.JLabel();
        lblErrorMessageAvd1 = new javax.swing.JLabel();
        jLblErrorMessageDate2 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setText("Förnamn");
        nameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFieldMouseClicked(evt);
            }
        });

        surnameField.setText("Efternamn");
        surnameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                surnameFieldMouseClicked(evt);
            }
        });
        surnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameFieldActionPerformed(evt);
            }
        });

        adressField.setText("Adress");
        adressField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adressFieldMouseClicked(evt);
            }
        });

        emailField.setText("Epost");
        emailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFieldMouseClicked(evt);
            }
        });

        phoneNumField.setText("Telefon");
        phoneNumField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneNumFieldMouseClicked(evt);
            }
        });

        createButton.setText("Skapa");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        lblPersonelDetails.setText("Skapa ny anställd");

        jTxtAvdelning.setText("Avdelningsnummer");
        jTxtAvdelning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtAvdelningMouseClicked(evt);
            }
        });

        jTxtAvdelningarna.setColumns(20);
        jTxtAvdelningarna.setRows(5);
        try{
            jTxtAvdelningarna.setText(fetchAvdelningar());
        }
        catch(Exception e){}
        jScrollPane1.setViewportView(jTxtAvdelningarna);

        dateOfEmploymentField.setText("yyyy-mm-dd");

        jLblErrorMessageDate1.setForeground(new java.awt.Color(255, 0, 0));
        jLblErrorMessageDate1.setText("Felaktigt format på datum, 1111-11-11 har lagts in per automatik.");

        lblErrorMessageAvd1.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMessageAvd1.setText("Avdelningen existerar inte. Inget har lagts in. ");

        jLblErrorMessageDate2.setForeground(new java.awt.Color(255, 0, 0));
        jLblErrorMessageDate2.setText("vänligen uppdatera uppgiften i uppdateringsfunktionen.");

        errorLabel.setForeground(new java.awt.Color(244, 22, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPersonelDetails)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtAvdelning, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(phoneNumField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateOfEmploymentField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMessageAvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblErrorMessageDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblErrorMessageDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPersonelDetails)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateOfEmploymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(createButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLblErrorMessageDate1)
                        .addGap(5, 5, 5)
                        .addComponent(jLblErrorMessageDate2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessageAvd1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void surnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameFieldActionPerformed

    }//GEN-LAST:event_surnameFieldActionPerformed

    private void nameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFieldMouseClicked
        if (nameField.getText().equals("Förnamn")) {
            nameField.setText("");
        }

    }//GEN-LAST:event_nameFieldMouseClicked

    private void surnameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surnameFieldMouseClicked
        if (surnameField.getText().equals("Efternamn")) {
            surnameField.setText("");
        }
    }//GEN-LAST:event_surnameFieldMouseClicked

    private void adressFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adressFieldMouseClicked
        if (adressField.getText().equals("Adress")) {
            adressField.setText("");
        }
    }//GEN-LAST:event_adressFieldMouseClicked

    private void emailFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseClicked
        if (emailField.getText().equals("Epost")) {
            emailField.setText("");
        }
    }//GEN-LAST:event_emailFieldMouseClicked

    private void phoneNumFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNumFieldMouseClicked
        if (phoneNumField.getText().equals("Telefon")) {
            phoneNumField.setText("");
        }
    }//GEN-LAST:event_phoneNumFieldMouseClicked
       
    private int chooseRole (int role){
        if (role == 0){
            return 1;
        }
        else {
            return 2; 
        }
    }
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String newName = nameField.getText();
        String newSurname = surnameField.getText();
        String newAdress = adressField.getText();
        String newEmail = emailField.getText();
        String newPhonenumber = phoneNumField.getText();
        String newEmploymentDate = dateOfEmploymentField.getText();
        String newAvdelning = jTxtAvdelning.getText();
        
         ArrayList<String> errorList = new ArrayList<>();
         boolean errorFound = false;
        try {
            if (validering.fieldValidation(newAvdelning, "Avdelning")) {
                if (checkValidAvdelning(newAvdelning) == true) {
                    String newAid = idb.getAutoIncrement("anstalld", "aid");
                    String sqlQuerry = ("INSERT INTO ngo_2024.anstalld (aid, avdelning) VALUES (" + newAid + "," + newAvdelning + ");");
                    idb.insert(sqlQuerry);
                    
                    
//använd valideringsklass
                    if (validering.fieldValidation(newName, "Förnamn")) {
                        insertValue("fornamn", newName, newAid);
                    }
                    else {
                        insertValue("fornamn", "ej angivet", newAid);
                        errorList.add("Förnamn");
                        errorFound = true;
                    }
                    //använd valideringsklass
                    if (validering.fieldValidation(newSurname, "Efternamn")) {
                        insertValue("efternamn", newSurname, newAid);
                    }
                    else {
                        insertValue("efternamn", "ej angivet", newAid);
                        errorList.add("Efternamn");
                        errorFound = true;
                    }
                    //använd valideringsklass, validera datum TODO
                    if (validering.fieldValidation(newAdress, "Adress")) {
                        insertValue("adress", newAdress, newAid);
                    }
                    else {
                        insertValue("adress", "ej angivet", newAid);
                        errorList.add("Adress");
                        errorFound = true;
                    }
                    //använd valideringsklass, validera datum TODO
                    if (validering.fieldValidation(newEmail, "Epost")) {
                        insertValue("epost", newEmail, newAid);
                    }
                    else {
                        insertValue("epost", "ej angivet", newAid);
                        errorList.add("Epost");
                        errorFound = true;
                    }
                    //använd valideringsklass
                    if (validering.fieldValidation(newPhonenumber, "Telefon")) {
                        insertValue("telefon", newPhonenumber, newAid);
                    }
                    else {
                        insertValue("telefon", "ej angivet", newAid);
                        errorList.add("Telefon");
                        errorFound = true;
                    }
                    if (validering.fieldValidation(newEmploymentDate, "yyyy-mm-dd") && validering.checkDateFormat(newEmploymentDate)){
                        
                            insertValue("anstallningsdatum", newEmploymentDate, newAid);
                        } 
                        else 
                        {
                            jLblErrorMessageDate1.setVisible(true);
                            jLblErrorMessageDate2.setVisible(true);
                            insertValue("anstallningsdatum", "1111-11-11", newAid);
                            errorList.add("Startdatum");
                        errorFound = true;
                        }
                    insertValue("losenord", generateNewPassword(), newAid);

                    //makeAdminCheckBox.getAccessibleContext();
                    String insertIntoAdmin = ("INSERT INTO ngo_2024.admin (aid, behorighetsniva) VALUES (" + newAid + "," + 1 + ")");
                    idb.insert(insertIntoAdmin);
                    
                } else {
                    lblErrorMessageAvd1.setVisible(true);
                }
                if(errorFound) {
                errorLabel.setText(insertError(errorList)); }
                
            }
        } catch (InfException ex) {
            Logger.getLogger(NewProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createButtonActionPerformed
private String insertError(ArrayList<String> errorList) {
    if (errorList == null || errorList.isEmpty()) {
        return "Inga felaktiga värden hittades."; 
    }
    
    StringBuilder message = new StringBuilder();
    for (int i = 0; i < errorList.size(); i++) {
        if (i > 0) {
            message.append(", ");
        }
        message.append(errorList.get(i));
    }
    return "Följande rutor hade felaktiga värden: " + message.toString(); 
}

    private void jTxtAvdelningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtAvdelningMouseClicked
        // TODO add your handling code here:
        if (jTxtAvdelning.getText().equals("Avdelningsnummer")) {
            jTxtAvdelning.setText("");
        }
    }//GEN-LAST:event_jTxtAvdelningMouseClicked

    /**
     * Metod som sätter in värden i databasen på senast skapde rad.
     *
     * @param column
     * @param value
     * @param newAid
     * @throws InfException
     */
    private void insertValue(String column, String value, String newAid) throws InfException {
        String sqlQuerry = ("UPDATE ngo_2024.anstalld t SET t." + column + " = '" + value + "' WHERE t.aid = " + newAid + ";");
        idb.update(sqlQuerry);
    }

    /**
     * Genererar nytt lösenord baserat på random klassen
     *
     * @return nyttLösenord
     */
    private String generateNewPassword() {
        // TODO add your handling code here:
        // TODO PROGRAMMERA SÅ ETT RANDOM LÖSEN SKAPAS OCH LÄGG IN I DATABAS UNDER RÄTT AID.
        String lowercase = "abcdefghijklmnopqrstuvwxyz";
        String uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String numbers = "0123456789";

        String allChars = lowercase + uppercase + numbers;

        Random r = new Random();

        String newPassword = "" + allChars.charAt(r.nextInt(0, allChars.length()));
        for (int i = 0; i < 12; i++) {
            int numb = r.nextInt(0, allChars.length());
            newPassword = newPassword + allChars.charAt(numb);
        }
        return newPassword;
    }

    public String fetchAvdelningar() throws InfException {
        ArrayList<String> avdelningsNamn = idb.fetchColumn("Select namn from avdelning;");
        ArrayList<String> avdelningsNummer = idb.fetchColumn("Select avdid from avdelning;");

        String message = "";
        String contentName = null;
        String contentNumber = null;
        for (int i = 0; i < avdelningsNamn.size(); i++) {
            contentName = avdelningsNamn.get(i);
            contentNumber = avdelningsNummer.get(i);
            message = message + "\n" + contentNumber + "\n" + contentName + "\n";
        }
        return message.trim();
    }

    public Boolean checkValidAvdelning(String avdelning) throws InfException {
        {
            Boolean avdelningExist = false;
            String avdelningsID = "";
            ArrayList<String> avdelningsNummer = idb.fetchColumn("Select avdid from avdelning;");
            for (int i = 0; i < avdelningsNummer.size(); i++) {
                avdelningsID = avdelningsNummer.get(i);
                if (avdelningsID.equals(avdelning)) {
                    avdelningExist = true;
                }
            }
            return avdelningExist;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewPersonel().setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(NewPersonel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adressField;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dateOfEmploymentField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLblErrorMessageDate1;
    private javax.swing.JLabel jLblErrorMessageDate2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAvdelning;
    private javax.swing.JTextArea jTxtAvdelningarna;
    private javax.swing.JLabel lblErrorMessageAvd1;
    private javax.swing.JLabel lblPersonelDetails;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneNumField;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
