/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NGO2024;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author meldi
 */
public class SamarbetspartnerLista extends javax.swing.JFrame {
    private InfDB idb;
    private static String pid;
    private static String userAid;
    
    public SamarbetspartnerLista(String pid, String userAid) throws InfException {
        
        this.pid = "4";
        this.userAid = userAid;
        
        idb = new InfDB("ngo_2024", "3306", "dbAdmin2024", "dbAdmin2024PW");
        initComponents();
        felmeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        partnerList = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        namnField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        createNewButton = new javax.swing.JButton();
        felmeddelande = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        partnerList.setColumns(20);
        partnerList.setRows(5);
        try {
            partnerList.setText(fetchUserProjects());
        }
        catch (InfException e) {}
        jScrollPane1.setViewportView(partnerList);

        addButton.setText("Lägg till partner");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Partner");

        namnField.setText("Namn");

        deleteButton.setText("Ta bort partner");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        createNewButton.setText("Skapa ny partner");
        createNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewButtonActionPerformed(evt);
            }
        });

        felmeddelande.setText("A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(createNewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namnField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(felmeddelande))
                            .addComponent(deleteButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(felmeddelande)
                        .addGap(24, 24, 24)
                        .addComponent(createNewButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String namn = namnField.getText();
        
        try {
            String sqlFraga = idb.fetchSingle("SELECT pid FROM partner WHERE namn = '" + namn +"';");
            idb.insert("INSERT INTO ngo_2024.projekt_partner (pid, partner_pid) VALUES ( "+ pid + " , " + sqlFraga +" );" );
                        partnerList.setText(fetchUserProjects());

            System.out.println(sqlFraga);
        } catch (InfException ex) {
            Logger.getLogger(SamarbetspartnerLista.class.getName()).log(Level.SEVERE, null, ex);
            felmeddelande.setVisible(true);
            felmeddelande.setText("Partner finns redan på projekt");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String namn = namnField.getText();
        
        try {
            String sqlFraga = idb.fetchSingle("SELECT pid FROM partner WHERE namn = '" + namn +"';");
            idb.delete("DELETE FROM ngo_2024.projekt_partner WHERE pid = '" + pid + "' AND partner_pid = '" + sqlFraga+ "';" );
                        partnerList.setText(fetchUserProjects());

            System.out.println(sqlFraga);
            
            
        } catch (InfException ex) {
            Logger.getLogger(SamarbetspartnerLista.class.getName()).log(Level.SEVERE, null, ex);
            felmeddelande.setVisible(true);
            felmeddelande.setText("Partner finns inte på projekt");
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void createNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewButtonActionPerformed
        try {
            // TODO add your handling code here:
            new NewPartner(pid, userAid).setVisible(true);
        } catch (InfException ex) {
            Logger.getLogger(SamarbetspartnerLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createNewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SamarbetspartnerLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SamarbetspartnerLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SamarbetspartnerLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SamarbetspartnerLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SamarbetspartnerLista(pid, userAid).setVisible(true);
                } catch (InfException ex) {
                    Logger.getLogger(SamarbetspartnerLista.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public String fetchUserProjects() throws InfException {
        ArrayList<String> samarbetsPartnerNamn = idb.fetchColumn("select namn from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
        ArrayList<String> samarbetsPartnerKontaktPerson = idb.fetchColumn("select kontaktperson from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
        ArrayList<String> samarbetsPartnerKontaktEpost = idb.fetchColumn("select kontaktepost from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
        ArrayList<String> samarbetsPartnerTelefon = idb.fetchColumn("select telefon from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
        ArrayList<String> samarbetsPartnerAdress = idb.fetchColumn("select adress from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
        ArrayList<String> samarbetsPartnerBranch = idb.fetchColumn("select branch from partner where pid in (select partner_pid from projekt_partner where pid in (select pid from projekt where projektchef = 4))");
       
        StringBuilder message = new StringBuilder();
        for (int i = 0; i < samarbetsPartnerNamn.size(); i++) {
        message.append("\nNamn: ").append(samarbetsPartnerNamn.get(i))
                .append("\nKontaktperson: ").append(samarbetsPartnerKontaktPerson.get(i))
                .append("\nEpost: ").append(samarbetsPartnerKontaktEpost.get(i))
                .append("\nTelefon: ").append(samarbetsPartnerTelefon.get(i)).append("\nAdress: ").append(samarbetsPartnerAdress.get(i)).append("\nBranch: ").append(samarbetsPartnerBranch.get(i)).append("\n");
    }
               
    return message.toString().trim();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton createNewButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel felmeddelande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField namnField;
    private javax.swing.JTextArea partnerList;
    // End of variables declaration//GEN-END:variables
}
